CC_Zone_3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
]

blog/urls.py
from django.conf.urls import url
from blog import views

#template urls
app_name='blog'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'profile/(?P<username>[a-zA-Z0-9]+)$', views.show_profile),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    #creating relationship
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #Add any additional attributes you want
    picture = models.ImageField(upload_to='profile_pic', blank=True)
    def __str__(self):
        return self.user.username

class Post(models.Model):
    author = models.ForeignKey('blog.UserProfileInfo',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True, null=True)
    def publish(self):
        self.published_date=timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comments=True)
    def get_absolute_url(self):
        return reverse("post_detail",kwargs={'pk':self.pk})
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post',related_name='comments',on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=True)
    def approve(self):
        self.approved_comment = True
        self.save()
    def get_absolute_url(self):
        return reverse('post_list')
    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from blog.models import UserProfileInfo
from django.contrib.auth.models import User
import re


def check_for_bitmail(value):
   if not re.match('f201[0-9][0-9]*4@pilani.bits-pilani.ac.in', value):
        raise forms.ValidationError("Not a bitsian!")


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(validators=[check_for_bitmail])
    class Meta():
        model = User
        fields = ('username','email','password',)

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('picture',)

blog/views.py
from django.shortcuts import render
from blog.models import UserProfileInfo,Post,Comment
from blog.forms import UserProfileInfoForm, UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django import forms
# Create your views here.


def index(request):
    return render(request,'blog/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm(data=request.GET)
    return render(request, 'blog/registration.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'registered':registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Login Failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Incorrect Credentials")
    else:
        return render(request,'blog/login.html',{})

@login_required
def show_profile(request):
    username = User.username
    user = User.objects.get(username=username)
    return render(request, 'blog/profile.html', {"user": user})

templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

</head>
<body background="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAz69oPZkliM1-55mnVYoSUJYdRVwgeS2R7CJTWMNWVMmfXuPCwQ">
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav bg-dark">
            <li><a class="navbar-brand" href="{% url 'index' %}"><img src="http://i63.tinypic.com/a26pnp.png" align="left"></a></li>
            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="">New post</a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a> </li>
            {% endif %}
            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'blog:show_profile' %}">User Profile</a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'blog:register' %}">Register</a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'blog:user_login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

templates/blog/index.html
<!DOCTYPE html>
{% extends "blog/base.html" %}
{% block block_body %}
{% if user.is_authenticated %}

{% else %}

{% endif %}

{% endblock %}

templates/blog/login.html
{% extends 'blog/base.html' %}
{% load staticfiles %}


{% block body_block %}
	<div class="dubba">
        <h1>Log in</h1>
        <form action="{% url 'blog:user_login' %}" method="post">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Username"><br>
            <label for="password">Password</label>
            <input type="password" name="password"><br><br>
            <input type="submit" name="" value="Log in" align="middle">
        </form>
	</div>
	<style type="text/css">
        h1{
            text-align: center;
        }
		.dubba{
			border-radius: 10px;
			border: 2px solid black;
			background-color: white;
			font-family: sans-serif;
			text-align: center;
			height: 300px;
			width:  300px;
			margin-top: 50px;
			margin-left: 500px;
			box-shadow: 5px 10px;
		}
	</style>
{% endblock %}

templates/blog/profile.html
<!DOCTYPE html>
{% extends "blog/base.html" %}
{% block block_body %}
{% if user.is_authenticated %}
    <div class="dubba">
        <h3>User: {{ user.username }}</h3>
        <h3>Email: {{ user.email }}</h3>
	</div>
	<style type="text/css">
        h1{
            text-align: center;
        }
		.dubba{
			border-radius: 10px;
			border: 2px solid black;
			background-color: white;
			font-family: sans-serif;
			text-align: center;
			height: 300px;
			width:  1200px;
			margin-top: 50px;
			margin-left: 100px;
			box-shadow: 5px 10px;
		}
	</style>
{% endif %}
{% endblock %}

templates/blog/registration.html
{% extends 'blog/base.html' %}
{% load staticfiles %}


{% block body_block %}
	<div class="dubba">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register here!</h1>
            <form method="post" enctype="multipart/form-data">
            <div class="container" align="left">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
            </div>
            </form>
        {% endif %}
	</div>
	<style type="text/css">
        h1{
            text-align: center;
        }
		.dubba{
			border-radius: 10px;
			border: 2px solid black;
			background-color: white;
			font-family: sans-serif;
			text-align: center;
			height: 300px;
			width:  1200px;
			margin-top: 50px;
			margin-left: 100px;
			box-shadow: 5px 10px;
		}
	</style>
{% endblock %}